import { Settings } from "lucide-react";
import { useState } from "react";
import type { FormEvent } from "react";
import { PageHeader } from "../../components/layout/AppLayout";
import { StatGrid } from "../../components/player/StatGrid";
import { Avatar } from "../../components/ui/Avatar";
import type { Profile, ProfileUpdate, Role } from "../../types/api";

const roles: Role[] = ["Rifler", "AWPer", "IGL", "Support", "Lurker", "Entry"];
export function ProfilePage({ profile, edit, settings }: { profile: Profile; edit: () => void; settings: () => void }) { return <><PageHeader title="Мой профиль" action={<button className="icon-button" onClick={settings} aria-label="Настройки"><Settings /></button>} /><section className="page-body"><div className="profile-card"><div className="profile-summary"><Avatar src={profile.avatar_url} name={profile.faceit_nickname} size="lg" /><div><h2>{profile.faceit_nickname}</h2><p className={profile.is_online ? "online-text" : ""}>{profile.is_online ? "Онлайн" : "Не в сети"}</p></div></div>{profile.bio && <div className="profile-bio"><span>О себе</span><p>{profile.bio}</p></div>}<StatGrid data={profile.statistics} /><div className="meta-grid"><div><span>Основная роль</span><strong>{profile.primary_role}</strong></div><div><span>Поиск</span><strong>{profile.is_searching ? "Включён" : "Выключен"}</strong></div>{profile.secondary_role && <div><span>Вторая роль</span><strong>{profile.secondary_role}</strong></div>}<div><span>Разница ELO</span><strong>±{profile.preferences.max_elo_difference}</strong></div></div><button className="button secondary" onClick={edit}>Редактировать профиль</button></div></section></>; }

export function ProfileEditor({ profile, save, close, busy }: { profile: Profile; save: (data: ProfileUpdate) => void; close: () => void; busy: boolean }) {
  const [data, setData] = useState<ProfileUpdate>({ bio: profile.bio, primary_role: profile.primary_role as Role, secondary_role: profile.secondary_role as Role | null, playstyle: profile.playstyle as ProfileUpdate["playstyle"], preferred_maps: profile.preferred_maps, languages: profile.languages, microphone: profile.microphone, schedule: profile.schedule, country_code: profile.country_code, birth_year: profile.birth_year, is_searching: profile.is_searching });
  const submit = (e: FormEvent) => { e.preventDefault(); save(data); };
  return <section className="modal-page"><header><button onClick={close}>Отмена</button><h1>Редактировать</h1><span /></header><form className="form panel" onSubmit={submit}><label>О себе<textarea maxLength={500} value={data.bio} onChange={(e) => setData({ ...data, bio: e.target.value })} /></label><div className="two-columns"><label>Основная роль<select value={data.primary_role} onChange={(e) => setData({ ...data, primary_role: e.target.value as Role })}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label><label>Вторая роль<select value={data.secondary_role ?? ""} onChange={(e) => setData({ ...data, secondary_role: (e.target.value || null) as Role | null })}><option value="">Нет</option>{roles.map((role) => <option key={role}>{role}</option>)}</select></label></div><label>Стиль игры<select value={data.playstyle ?? ""} onChange={(e) => setData({ ...data, playstyle: (e.target.value || null) as ProfileUpdate["playstyle"] })}><option value="">Не указан</option><option>Агрессивный</option><option>Сбалансированный</option><option>Тактический</option></select></label><label>Языки (через запятую)<input value={data.languages.join(", ")} onChange={(e) => setData({ ...data, languages: e.target.value.split(",").map((x) => x.trim()).filter(Boolean) })} /></label><label>Расписание<input maxLength={80} value={data.schedule ?? ""} onChange={(e) => setData({ ...data, schedule: e.target.value || null })} /></label><label className="toggle-row"><span>Ищу команду</span><input type="checkbox" checked={data.is_searching} onChange={(e) => setData({ ...data, is_searching: e.target.checked })} /></label><button disabled={busy} className="button primary">{busy ? "Сохраняем…" : "Сохранить"}</button></form></section>;
}
