import { RotateCcw } from "lucide-react";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { PageHeader } from "../../components/layout/AppLayout";
import { StatGrid } from "../../components/player/StatGrid";
import { ErrorState, Skeleton } from "../../components/ui/States";
import type { Role, SearchPreferences, Statistics } from "../../types/api";

const roles: Role[] = ["Rifler", "Support", "IGL", "AWPer", "Entry", "Lurker"];
const defaults: SearchPreferences = { elo_min: 0, elo_max: 4000, max_elo_difference: 250, roles: [], language: null, schedule: null, online_only: false };
export function StatisticsPage({ preferences, statistics, loading, error, save }: { preferences: SearchPreferences | null; statistics: Statistics | null; loading: boolean; error: string; save: (p: SearchPreferences) => Promise<void> }) {
  const [form, setForm] = useState(preferences ?? defaults); const [busy, setBusy] = useState(false);
  useEffect(() => { if (preferences) setForm(preferences); }, [preferences]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); try { await save(form); } finally { setBusy(false); } };
  const toggleRole = (role: Role) => setForm({ ...form, roles: form.roles.includes(role) ? form.roles.filter((x) => x !== role) : [...form.roles, role] });
  return <><PageHeader title="Статистика и фильтры" /><section className="page-body">{loading ? <Skeleton tall /> : error ? <ErrorState message={error} /> : <><form className="panel filter-form" onSubmit={submit}><div className="section-title"><h2>Фильтры поиска</h2><button type="button" className="icon-button" onClick={() => setForm(defaults)} aria-label="Сбросить фильтры"><RotateCcw /></button></div><div className="two-columns"><label>ELO от<input type="number" min="0" max="5000" value={form.elo_min} onChange={(e) => setForm({ ...form, elo_min: Number(e.target.value) })} /></label><label>ELO до<input type="number" min="0" max="5000" value={form.elo_max} onChange={(e) => setForm({ ...form, elo_max: Number(e.target.value) })} /></label></div><label>Максимальная разница: ±{form.max_elo_difference}<input type="range" min="50" max="1500" step="50" value={form.max_elo_difference} onChange={(e) => setForm({ ...form, max_elo_difference: Number(e.target.value) })} /></label><fieldset><legend>Роли</legend><div className="role-grid">{roles.map((role) => <button type="button" className={form.roles.includes(role) ? "selected" : ""} onClick={() => toggleRole(role)} key={role}>{role}</button>)}</div></fieldset><label>Язык<input placeholder="ru, en…" maxLength={16} value={form.language ?? ""} onChange={(e) => setForm({ ...form, language: e.target.value || null })} /></label><label>Расписание<input maxLength={80} value={form.schedule ?? ""} onChange={(e) => setForm({ ...form, schedule: e.target.value || null })} /></label><label className="toggle-row"><span>Только онлайн</span><input type="checkbox" checked={form.online_only} onChange={(e) => setForm({ ...form, online_only: e.target.checked })} /></label><button className="button primary" disabled={busy}>{busy ? "Сохраняем…" : "Применить фильтры"}</button></form>{statistics && <section className="panel stats-section"><h2>Моя статистика</h2><StatGrid data={statistics} />{statistics.recent_form.length > 0 && <div className="recent-form">{statistics.recent_form.map((result, i) => <span className={result === "W" ? "win" : "loss"} key={i}>{result}</span>)}</div>}<MapDistribution items={statistics.map_distribution} /></section>}</>}</section></>;
}
function MapDistribution({ items }: { items: Record<string, number> }) { const rows = Object.entries(items).sort((a,b) => b[1]-a[1]); const max = Math.max(1, ...rows.map(([,v]) => v)); if (!rows.length) return null; return <div className="map-distribution"><h3>Карты</h3>{rows.map(([name, value]) => <div key={name}><span>{name}</span><i><b style={{ width: `${value / max * 100}%` }} /></i><strong>{value}</strong></div>)}</div>; }
