import { ChevronRight, Inbox, MessageSquare, Plus, Search, Send, Settings2, UserRound, UsersRound, X } from "lucide-react";
import { useState } from "react";
import type { MatchItem, PlayerDetails, Profile, SearchPreferences, Statistics, Tab } from "../types/api";

const art="/assets/tactical-operator.png";
const games=[{name:"CS2",sub:"COUNTER-STRIKE 2",tone:"gold"},{name:"VALORANT",sub:"TACTICAL 5V5",tone:"red"},{name:"STANDOFF 2",sub:"MOBILE FPS",tone:"orange"}];
const modes=["COMPETITIVE","PREMIER","FACEIT","CHILL"];

export function TacticalApp({profile,player,matches,statistics,loading,busy,tab,onTab,onSwipe,onLoadMatches,onEdit,onSettings,onOpenPlayer}:{profile:Profile;player:PlayerDetails|null;matches:MatchItem[];preferences:SearchPreferences|null;statistics:Statistics|null;loading:boolean;busy:boolean;tab:Tab;onTab:(tab:Tab)=>void;onSwipe:(d:"like"|"dislike")=>void;onLoadMatches:()=>void;onSaveFilters:(p:SearchPreferences)=>Promise<void>;onEdit:()=>void;onSettings:()=>void;onOpenPlayer:(id:number)=>void}){
 const [game,setGame]=useState(0); const [mode,setMode]=useState(0); const [count,setCount]=useState(1); const [style,setStyle]=useState(56); const [searching,setSearching]=useState(false);
 const nav=(next:Tab)=>{onTab(next);if(next==="matches")onLoadMatches()};
 return <main className="cu-shell"><div className="cu-noise"/><header className="cu-top"><button className="cu-close"><X/></button><b>CLUTCHUP</b><span/><div className="cu-status"><i/><i/><i/><i/></div></header>
  <div className="cu-scroll">{tab==="search"&&<>
   <section className="cu-game"><SectionMark no="01" title="CHOOSE\nYOUR GAME"/><div className="cu-game-deck">{games.map((g,i)=><button key={g.name} onClick={()=>setGame(i)} className={`cu-game-card ${g.tone} ${i===game?"active":""}`} style={{"--d":i-game} as React.CSSProperties}><img src={art}/><small>0{i+1}</small><strong>{g.name}</strong><span>{g.sub}</span></button>)}</div><div className="cu-dots">{games.map((_,i)=><i className={i===game?"active":""} key={i}/>)}</div></section>
   <section className="cu-finder"><div className="cu-controls"><SectionMark no="02" title="FIND\nYOUR PARTY"/><p>PLAY ALONE TODAY.<br/>WIN AS A TEAM.</p><ControlLabel label="MODE" value={games[game].name}/><div className="cu-tabs">{modes.map((x,i)=><button className={i===mode?"active":""} onClick={()=>setMode(i)} key={x}>{x}</button>)}</div><ControlLabel label="PREFERRED PARTY PLAYERS" value={`+${count}`}/><div className="cu-tabs count">{[1,2,3,4].map(x=><button className={x===count?"active":""} onClick={()=>setCount(x)} key={x}>+{x}</button>)}</div><ControlLabel label="PLAY STYLE"/><input type="range" value={style} onChange={e=>setStyle(+e.target.value)}/><div className="cu-range"><span>CHILL</span><span>TRYHARD</span></div><button className="cu-cta" onClick={()=>setSearching(true)}>FIND PARTY <ChevronRight/></button></div><div className="cu-card-zone">{searching?<Radar stop={()=>setSearching(false)}/>:loading?<div className="cu-loading">ACQUIRING SIGNAL...</div>:player?<PlayerCard player={player} busy={busy} pass={()=>onSwipe("dislike")} party={()=>onSwipe("like")} open={()=>onOpenPlayer(player.user_id)}/>:<div className="cu-loading">NO SIGNALS IN RANGE</div>}</div></section>
  </>}
  {tab==="matches"&&<Parties matches={matches} open={onOpenPlayer}/>}
  {tab==="statistics"&&<InboxScreen player={player}/>}
  {tab==="profile"&&<ProfileScreen profile={profile} stats={statistics} edit={onEdit} settings={onSettings}/>}
  </div><nav className="cu-nav">{[["search","FIND",Search],["matches","PARTIES",UsersRound],["statistics","INBOX",Inbox],["profile","PROFILE",UserRound]].map(([id,label,Icon])=><button key={id as string} className={tab===id?"active":""} onClick={()=>nav(id as Tab)}><Icon/><span>{label as string}</span></button>)}</nav>
 </main>
}

function SectionMark({no,title}:{no:string;title:string}){return <div className="cu-mark"><span>{no}</span><h2>{title.split("\n").map(x=><i key={x}>{x}</i>)}</h2></div>}
function ControlLabel({label,value}:{label:string;value?:string}){return <div className="cu-label"><span>{label}</span>{value&&<b>{value}</b>}</div>}
function PlayerCard({player,busy,pass,party,open}:{player:PlayerDetails;busy:boolean;pass:()=>void;party:()=>void;open:()=>void}){return <div className="cu-stack"><i/><i/><article className="cu-player"><div className="cu-player-art"><img src={player.avatar_url||art}/><span className="online"><i/> ONLINE</span><small>~12m</small></div><div className="cu-player-data"><h3>{player.faceit_nickname}<em> ✓</em></h3><p>LVL {player.statistics.skill_level} · {player.country_code||"EUROPE"}</p><div className="cu-badges"><b>{player.primary_role}</b>{player.secondary_role&&<b>{player.secondary_role}</b>}</div><strong className="elo">◢ FACEIT {player.statistics.elo} ELO</strong><small>LOOKING FOR</small><div className="cu-tags"><span>{modes[0]}</span><span>{player.playstyle||"AIM"}</span>{player.microphone&&<span>MIC YES</span>}</div></div><div className="cu-card-actions"><button disabled={busy} onClick={pass}><X/> IGNORE</button><button onClick={open}>PROFILE</button><button disabled={busy} onClick={party}><Plus/> PARTY</button></div></article></div>}
function Radar({stop}:{stop:()=>void}){return <div className="cu-radar"><div className="radar-ring"><i/><i/><i/><span/></div><strong>SEARCHING<br/>FOR PLAYERS</strong><small>SIGNAL RANGE / EUROPE</small><button onClick={stop}>CANCEL SEARCH</button></div>}
function Parties({matches,open}:{matches:MatchItem[];open:(id:number)=>void}){return <section className="cu-page"><header><SectionMark no="04" title="MY PARTIES"/><Settings2/></header><div className="cu-page-tabs"><b>ACTIVE</b><span>INVITES</span><span>HISTORY</span></div><div className="cu-party-list">{matches.length?matches.map((m,i)=><button onClick={()=>open(m.user_id)} key={m.user_id}><img src={m.avatar_url||art}/><div><strong>{m.faceit_nickname}</strong><span>Competitive / +{i%3+1}</span></div><small>{i+2} / 5</small><i/></button>):<div className="cu-empty"><UsersRound/><b>NO ACTIVE PARTIES</b><span>Send a signal to start one.</span></div>}</div><button className="cu-fab"><Plus/></button></section>}
function InboxScreen({player}:{player:PlayerDetails|null}){return <section className="cu-page cu-chat"><header><SectionMark no="05" title="PARTY COMMS"/><MessageSquare/></header><div className="cu-chat-head"><img src={player?.avatar_url||art}/><div><b>{player?.faceit_nickname||"PARTY CHANNEL"}</b><span>3 / 5 · ONLINE</span></div></div><div className="messages"><p><b>m1CKE</b>Let's delay A and hit lower</p><p className="voice"><i>▶</i><span>▮▯▮▮▯▮▯▮▮▮▯</span><small>0:12</small></p><p className="me"><b>YOU</b>I'll flash over smoke</p><p><b>a1rtek</b>I can join now</p></div><div className="cu-compose"><input placeholder="Type a message..."/><button><Send/></button></div></section>}
function ProfileScreen({profile,stats,edit,settings}:{profile:Profile;stats:Statistics|null;edit:()=>void;settings:()=>void}){const s=stats||profile.statistics;return <section className="cu-page cu-profile"><header><SectionMark no="06" title="PLAYER PROFILE"/><button onClick={settings}><Settings2/></button></header><div className="profile-hero"><img src={profile.avatar_url||art}/><span>CLUTCHUP / VERIFIED</span></div><div className="profile-info"><h1>{profile.faceit_nickname}<em> ✓</em></h1><p>LVL {s.skill_level} · {profile.country_code||"EUROPE"}</p><strong>◢ FACEIT {s.elo} ELO</strong><p className="bio">{profile.bio||"I play for fun. I win for the team. I don't chase numbers. I remember calls."}</p><div className="cu-tags"><span>{profile.primary_role}</span><span>{profile.playstyle||"TACTICAL"}</span><span>5K+</span></div><div className="stat-row"><div><span>WINS</span><b>{s.matches||0}</b></div><div><span>WIN RATE</span><b>{s.win_rate||0}%</b></div><div><span>MATCHES</span><b>{s.matches||0}</b></div></div><button className="cu-cta" onClick={edit}>EDIT PROFILE <ChevronRight/></button></div></section>}
