import { Inbox,Plus,Search,UserRound,UsersRound,X } from "lucide-react";
import { useState } from "react";
import { endpoints } from "../../api/client";
import { useApp } from "../../app/AppProvider";
import { GAME_CONFIG } from "../../config/games";
import type { AppTab,Party,PartyCreate } from "../../types/api";
import { ControlledGameSwitcher } from "../game/ControlledGameSwitcher";
import { PartyCard } from "../party/PartyCard";

export function ProductShell(){const app=useApp();const [create,setCreate]=useState(false),[detail,setDetail]=useState<Party|null>(null),[switcher,setSwitcher]=useState(false);const config=GAME_CONFIG[app.game];return <main className="product-shell"><header className="product-header"><b>CLUTCHUP</b><button onClick={()=>setSwitcher(true)}>{config.shortName}⌄</button></header><div className="product-scroll" aria-live="polite">{app.error&&<div className="api-error">{app.error}<button onClick={()=>void app.reload()}>RETRY</button></div>}{app.tab==="find"&&<section className="find-page"><div className="find-title"><span>FIND</span><h1>FIND YOUR PARTY</h1><p>Pick a game. Join an open party. Play.</p></div><QuickFilters/><div className="feed-head"><h2>OPEN PARTIES</h2><button onClick={()=>setCreate(true)}><Plus/> CREATE PARTY</button></div>{app.loading?<CardsSkeleton/>:app.parties.length?<div className="party-feed">{app.parties.map(p=><PartyCard key={p.id} party={p} onJoin={app.join} onOpen={setDetail}/>)}</div>:<Empty title="NO OPEN PARTIES" action={()=>setCreate(true)}/>}</section>}{app.tab==="parties"&&<ListPage title="MY PARTIES" items={app.mine} join={app.join} open={setDetail} create={()=>setCreate(true)}/>} {app.tab==="inbox"&&<InboxPage/>}{app.tab==="profile"&&<ProfilePage/>}</div><BottomNav/>{switcher&&<div className="sheet"><button className="sheet-close" onClick={()=>setSwitcher(false)}><X/></button><h2>CHOOSE YOUR GAME</h2><ControlledGameSwitcher value={app.game} onChange={v=>{app.setGame(v);setSwitcher(false)}}/></div>}{create&&<CreateParty close={()=>setCreate(false)} submit={async data=>{await app.create(data);setCreate(false)}}/>}{detail&&<PartyDetail party={detail} close={()=>setDetail(null)} join={app.join}/>}</main>}

function QuickFilters(){const {game,filters,setFilters}=useApp();const modes=GAME_CONFIG[game].modes;return <div className="quick-filters"><label>MODE<select value={filters.mode||modes[0]} onChange={e=>setFilters({...filters,mode:e.target.value})}>{modes.map(x=><option key={x}>{x}</option>)}</select></label><label>PARTY SIZE<div className="slot-buttons">{[1,2,3,4].map(x=><button className={filters.freeSlots===x?"active":""} onClick={()=>setFilters({...filters,freeSlots:x})} key={x}>+{x}</button>)}</div></label><label>VIBE<input type="range" value={filters.vibe} onChange={e=>setFilters({...filters,vibe:+e.target.value})}/><span>CHILL <i/> TRYHARD</span></label></div>}
function BottomNav(){const {tab,setTab}=useApp();const items:[AppTab,string,typeof Search][]=[["find","FIND",Search],["parties","PARTIES",UsersRound],["inbox","INBOX",Inbox],["profile","PROFILE",UserRound]];return <nav className="product-nav">{items.map(([id,label,Icon])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon/><span>{label}</span></button>)}</nav>}
function ListPage({title,items,join,open,create}:{title:string;items:Party[];join:(id:number)=>Promise<void>;open:(p:Party)=>void;create:()=>void}){return <section className="list-page"><div className="page-heading"><h1>{title}</h1><button onClick={create}><Plus/> CREATE</button></div>{items.length?<div className="party-feed">{items.map(p=><PartyCard key={p.id} party={p} onJoin={join} onOpen={open}/>)}</div>:<Empty title="NO ACTIVE PARTIES" action={create}/>}</section>}
function InboxPage(){const {requests,user,decide}=useApp();return <section className="list-page"><div className="page-heading"><h1>INBOX</h1></div>{requests.length?<div className="request-list">{requests.map(r=><article key={r.id}><div><b>{r.requester_user_id===user?.user_id?"YOUR REQUEST":`${r.requester_name} WANTS TO JOIN`}</b><span>{r.party_title} · {r.status}</span></div>{r.status==="PENDING"&&r.requester_user_id!==user?.user_id&&<p><button onClick={()=>void decide(r.id,false)}>REJECT</button><button onClick={()=>void decide(r.id,true)}>ACCEPT</button></p>}</article>)}</div>:<Empty title="INBOX IS CLEAR"/>}</section>}
function ProfilePage(){const {user,gameProfile,game}=useApp();if(!user)return <CardsSkeleton/>;const connect=async()=>{if(user.faceit_connected)return;const {authorization_url}=await endpoints.oauthStart();window.location.assign(authorization_url)};return <section className="profile-page-new"><img src={user.avatar_url||"/assets/tactical-operator.png"} alt={user.display_name}/><h1>{user.display_name}</h1><p>{user.bio||"Your ClutchUp profile works across every game."}</p><div className="profile-facts"><span>{user.languages.join(" / ")||"NO LANGUAGE SET"}</span><span>{user.microphone?"MIC READY":"MIC OPTIONAL"}</span></div><article><b>{GAME_CONFIG[game].displayName}</b><span>{gameProfile?.nickname||"GAME PROFILE NOT SET"}</span>{game==="cs2"&&<button disabled={user.faceit_connected} onClick={()=>void connect()}>{user.faceit_connected?"FACEIT CONNECTED":"CONNECT FACEIT · OPTIONAL"}</button>}</article></section>}
function CreateParty({close,submit}:{close:()=>void;submit:(data:PartyCreate)=>Promise<void>}){const {game}=useApp();const cfg=GAME_CONFIG[game];const [data,setData]=useState<PartyCreate>({game,title:"",mode:cfg.modes[0],capacity:cfg.maxPartySize,vibe:50,language:null,mic_required:false,rank_min:null,rank_max:null,description:""});return <div className="sheet create-sheet"><button className="sheet-close" onClick={close}><X/></button><h2>CREATE PARTY</h2><form onSubmit={e=>{e.preventDefault();void submit(data)}}><label>TITLE<input required maxLength={80} value={data.title} onChange={e=>setData({...data,title:e.target.value})}/></label><label>MODE<select value={data.mode} onChange={e=>setData({...data,mode:e.target.value})}>{cfg.modes.map(x=><option key={x}>{x}</option>)}</select></label><label>CAPACITY<input type="number" min="2" max={cfg.maxPartySize} value={data.capacity} onChange={e=>setData({...data,capacity:+e.target.value})}/></label><label>LANGUAGE<input maxLength={16} value={data.language||""} onChange={e=>setData({...data,language:e.target.value||null})}/></label><label className="check"><input type="checkbox" checked={data.mic_required} onChange={e=>setData({...data,mic_required:e.target.checked})}/> MIC REQUIRED</label><label>DESCRIPTION<textarea maxLength={500} value={data.description} onChange={e=>setData({...data,description:e.target.value})}/></label><button className="primary-action">CREATE PARTY</button></form></div>}
function PartyDetail({party,close,join}:{party:Party;close:()=>void;join:(id:number)=>Promise<void>}){return <div className="sheet detail-sheet"><button className="sheet-close" onClick={close}><X/></button><span>{party.game.toUpperCase()} · {party.mode}</span><h2>{party.title}</h2><p>{party.description||"No additional details."}</p><div className="detail-members">{party.members.map(m=><div key={m.user_id}><img src={m.avatar_url||"/assets/tactical-operator.png"}/><span>{m.display_name}<small>{m.role}</small></span></div>)}</div><button className="primary-action" disabled={party.request_status==="PENDING"} onClick={()=>void join(party.id)}>{party.request_status==="PENDING"?"REQUESTED":"+ PARTY"}</button></div>}
function Empty({title,action}:{title:string;action?:()=>void}){return <div className="empty-state"><UsersRound/><b>{title}</b>{action&&<button onClick={action}>CREATE PARTY</button>}</div>}
function CardsSkeleton(){return <div className="party-feed"><i className="card-skeleton"/><i className="card-skeleton"/></div>}
