import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Locale = "en" | "ru";
const RU_COUNTRIES=new Set(["RU","BY","KZ","KG","AM","AZ","MD","TJ","TM","UZ"]),KEY="clutchup.locale";
const copy={
en:{find:"FIND",parties:"PARTIES",inbox:"INBOX",profile:"PROFILE",findTitle:"FIND\nYOUR PARTY",findCopy:"Open parties for {name}. Join in seconds.",openParties:"OPEN PARTIES",createParty:"CREATE PARTY",create:"CREATE",mode:"MODE",size:"SIZE",vibe:"VIBE",chill:"CHILL",balanced:"BALANCED",tryhard:"TRYHARD",noParties:"NO OPEN PARTIES",noPartiesText:"Try another mode or create your own party.",myParties:"MY PARTIES",active:"ACTIVE",invites:"INVITES",history:"HISTORY",noActive:"NO ACTIVE PARTIES",noActiveText:"Create a party or request to join one from Find.",activity:"ACTIVITY",inboxCopy:"Join requests and party activity.",inboxClear:"INBOX IS CLEAR",inboxClearText:"New join requests and updates will appear here.",gameProfiles:"GAME PROFILES",settings:"SETTINGS",appLanguage:"APP LANGUAGE",autoRegion:"Initially selected from FACEIT region",english:"English",russian:"Русский",regionMissing:"REGION NOT SET",languageMissing:"LANGUAGE NOT SET",micReady:"MIC READY",notConfigured:"NOT CONFIGURED",chooseGame:"CHOOSE YOUR GAME",searching:"SEARCHING FOR PARTIES",scanning:"Scanning open parties for your filters."},
ru:{find:"ПОИСК",parties:"ПАТИ",inbox:"ВХОДЯЩИЕ",profile:"ПРОФИЛЬ",findTitle:"НАЙДИ\nСВОЮ ПАТИ",findCopy:"Открытые пати для {name}. Присоединяйся за секунды.",openParties:"ОТКРЫТЫЕ ПАТИ",createParty:"СОЗДАТЬ ПАТИ",create:"СОЗДАТЬ",mode:"РЕЖИМ",size:"МЕСТА",vibe:"НАСТРОЙ",chill:"СПОКОЙНО",balanced:"БАЛАНС",tryhard:"ТРАЙХАРД",noParties:"НЕТ ОТКРЫТЫХ ПАТИ",noPartiesText:"Смени режим или создай свою пати.",myParties:"МОИ ПАТИ",active:"АКТИВНЫЕ",invites:"ПРИГЛАШЕНИЯ",history:"ИСТОРИЯ",noActive:"НЕТ АКТИВНЫХ ПАТИ",noActiveText:"Создай пати или отправь заявку через поиск.",activity:"АКТИВНОСТЬ",inboxCopy:"Заявки на вступление и события пати.",inboxClear:"ВХОДЯЩИХ НЕТ",inboxClearText:"Новые заявки и обновления появятся здесь.",gameProfiles:"ИГРОВЫЕ ПРОФИЛИ",settings:"НАСТРОЙКИ",appLanguage:"ЯЗЫК ПРИЛОЖЕНИЯ",autoRegion:"Изначально выбран по региону FACEIT",english:"English",russian:"Русский",regionMissing:"РЕГИОН НЕ УКАЗАН",languageMissing:"ЯЗЫК НЕ УКАЗАН",micReady:"МИКРОФОН ГОТОВ",notConfigured:"НЕ НАСТРОЕН",chooseGame:"ВЫБЕРИ ИГРУ",searching:"ИЩЕМ ПАТИ",scanning:"Проверяем открытые пати по твоим фильтрам."}} as const;
type CopyKey=keyof typeof copy.en;
type Value={locale:Locale;setLocale:(v:Locale)=>void;applyCountry:(v:string|null)=>void;t:(k:CopyKey,v?:Record<string,string>)=>string};
const Context=createContext<Value|null>(null);
export function LocaleProvider({children}:{children:ReactNode}){const [locale,setValue]=useState<Locale>(()=>(localStorage.getItem(KEY) as Locale|null)||"en");const setLocale=useCallback((v:Locale)=>{localStorage.setItem(KEY,v);localStorage.setItem(KEY+".manual","1");setValue(v)},[]);const applyCountry=useCallback((v:string|null)=>{if(localStorage.getItem(KEY+".manual")||!v)return;const next=RU_COUNTRIES.has(v.toUpperCase())?"ru":"en";localStorage.setItem(KEY,next);setValue(next)},[]);useEffect(()=>{document.documentElement.lang=locale},[locale]);const t=useCallback((k:CopyKey,vars?:Record<string,string>)=>Object.entries(vars||{}).reduce((s,[name,value])=>s.replace("{"+name+"}",value),copy[locale][k] as string),[locale]);const value=useMemo(()=>({locale,setLocale,applyCountry,t}),[locale,setLocale,applyCountry,t]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useLocale(){const value=useContext(Context);if(!value)throw new Error("LocaleProvider missing");return value}
